### ISSUE TITLE
Add conan_clean_remote()

### ISSUE THREAD

**Issue by goranbrkic** [conan-io/cmake-conan#149]
As we already have conan_add_remote(), it would be helpful to provide the ability to clean entire list of remotes.

This will be helpful in cases of private conan centrals.

**Comment by memsharded** [comment]
Actually, for private repos and custom private configuration in general, it  would be preferred to rely on "conan config install". In this way, all developers and CI get the same:

- The same remotes
- The same profiles
- the same custom settings.yml
- the same conan.conf values
- etc.

Otherwise, it would be executing "conan remote clean". I am not sure we should implement a cmake function for every possible conan command and subcommand, unless they have much extra added logic.

**Comment by goranbrkic** [comment]
Agreed.

Created https://github.com/conan-io/cmake-conan/issues/151 instead.
