### ISSUE TITLE
Support for no operating system

### ISSUE THREAD

**Issue by JoshCollins746** [conan-io/cmake-conan#150]
I have a project that compiles for a embedded system (based on an stm32 chip) that does not have an operating system. My cmake toolchain file sets the CMAKE_SYSTEM_NAME to "Generic" which seems to be the typical suggestion for this situation.

conan.cmake:105 creates a list of supported platforms (Windows Linux Macos Android iOS FreeBSD WindowsStore) and fails to build if the CMAKE_SYSTEM_NAME is not one of these.

I have managed to work around this temporarily by setting CMAKE_SYSTEM_NAME to one of the supported systems (i chose "iOS") when calling conan_cmake_run and reverting back to "Generic" after. I also have to get the CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, CMAKE_C_FLAGS and CMAKE_CXX_FLAGS and pass them via environment variables to get it to build. I end up with something like this:

    get_filename_component(path ${CMAKE_C_COMPILER} DIRECTORY)
    get_filename_component(c_compiler ${CMAKE_C_COMPILER} NAME)
    get_filename_component(cxx_compiler ${CMAKE_CXX_COMPILER} NAME)

    set(CMAKE_SYSTEM_NAME "iOS")
    conan_cmake_run(
      REQUIRES gsl_microsoft/2.0.0@bincrafters/stable
      BASIC_SETUP CMAKE_TARGETS NO_OUTPUT_DIRS
      BUILD missing
      GENERATORS cmake
      SETTINGS os=Linux
      SETTINGS arch=armv7
      SETTINGS compiler.threads=None
      ENV CC=${c_compiler}
      ENV CXX=${cxx_compiler}
      ENV CFLAGS=${CMAKE_C_FLAGS}
      ENV CXXFLAGS=${CMAKE_CXX_FLAGS}
      ENV LDFLAGS=${CMAKE_EXE_LINKER_FLAGS}
      ENV CONAN_CMAKE_GENERATOR=${CMAKE_GENERATOR}
    )
    set(CMAKE_SYSTEM_NAME "Generic")

My questions are 2 fold:
  1. Does conan the tool natively support OS-less systems? (Invoking conan install by hand seems to fail if os is not windows, linux or macos from memory).
  2. Should this conan.cmake script be able to handle this compiler and correctly pass all the settings to conan without me needing to do all the manual work above?

**Comment by czoido** [comment]
Hi @JoshCollins746,
Sorry for the superlate response. I just came into this proposing a fix for the issue you are commenting about the Generic platform.
For the rest of the question you can have a look at a similar issue: https://github.com/conan-io/cmake-conan/issues/284
The architecture, you will have to set it as an argument or in a profile yourself because right now there's no way to auto-detect it. For the compiler, I think there's no need to pass `CC`, `CXX`... as env vars, it should be detected and set correctly taking the settings that CMake detected.
