### ISSUE TITLE
Question: conanfile.txt with new api

### ISSUE THREAD

**Issue by tiolan** [conan-io/cmake-conan#326]
Hey,
does the new interface with conan_cmake_install() still allow providing a custom conanfile.txt via the CONANFILE argument?
Or do I need to configure the required packages with their options via conan_cmake_configure()?

Tried a lot, but did not succeed so far.
Only having all the required packages in the configure macro worked for me.

I am a bit confused and do not know when to youse which api. Do I need to mix them?
(run vs install)

One further question: should conan_cmake_autodetect also detect and set the processor architecture?

Thanks

**Comment by puetzk** [comment]
conan_cmake_install takes `PATH_OR_REFERENCE`. This is the same as what`conan install` command takes - a path to a conanfile.txt, conanfile.py, directory taking one of the above, or the name of a recipe/version@user/channel to search in the cache/remotes.

conan_cmake_configure() is just a way to generate a conanfile.txt from the CMakeLists.txt - if you already have one, you don't need that part.

conan_cmake_autodetect  would look at the CMAKE_SYSTEM_PROCESSOR, CMAKE_CXX_COMPILER_ID, etc, and try to guess at the right conan settings to use. The question here is whether you want CMake telling conan what settings to use (after enable_language), or conan telling cmake what compiler to set up for (before enable_language)

So yes, the old functionality of conan_cmake_run was split into 3 pieces - to fully recreate it you need to use all 3. But not everyone wanted all 3 parts - it would be perfectly reasonable to use only conan_cmake_install(), with a conanfile that was already present, and with a profile that gave conan the settings to use, and the conanbuildinfo.cmake configuring cmake accordingly, instead of the reverse.

**Comment by tiolan** [comment]
Got it, thanks a lot!
