### ISSUE TITLE
QUESTION: How do I use CONAN_CMAKE_FIND_ROOT_PATH in profiles with conan_cmake_install?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/cmake-conan#432]
Hi,

I'm cross-compiling a project and I have CONAN_CMAKE_FIND_ROOT_PATH, CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY, CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE and CONAN_CMAKE_SYSROOT set in the profile.

I use conan_cmake_install with "cmake" generator, I specify PROFILE_HOST, PROFILE_BUILD, SETTINGS_HOST, SETTINGS_BUILD, OPTIONS_HOST, OPTIONS_BUILD.

I also see that the appropriate parameters are proxied to "conan install". Also the conanbuildinfo.cmake files are generated
and loaded in CMakeLists.txt. 
However if I add some debug messages to print out the CONAN_CMAKE_FIND_ROOT_PATH* variables they are empty.

How can I make conan install to use those variables in the profile? I am using 1.48.1
Thanks,

**Comment by harsszegi** [comment]
Meh, CONAN_CMAKE_SYSTEM_NAME has to be defined as well in the profile, that specifies "cross-building mode", otherwise the others variables are not parsed by Conan

**Comment by memsharded** [comment]
Hi @harsszegi 

In any case, it is important to know that those generators are being deprecated and removed in 2.0. 
The new generators to use are ``CMakeDeps``, ``CMakeToolchain``, and are controlled by ``conf``, not by environment variables like. Also, the cross-compiling mode, should be using the 2 profiles approach: ``--profile:build=xxx --profile=host=yyyy``, because that is the way it will work in 2.0 too.

**Comment by harsszegi** [comment]
Hi @memsharded , yeah I am using conan install like that already (e.g separate build and host profiles), however (in 1.xx at least and with cmake and cmake_find_package at least) the code setting up the CMake environment requires that CONAN_CMAKE_SYSTEM_NAME would be set otherwise other CMake find_* related variables would not be filled.

Thank you very much for the heads up about the deprecation!
