### ISSUE TITLE
[question] How should the v0.16 functions be used?

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/cmake-conan#456]
From the current documentation, it is not clear how the new v0.16 functions should be used in practice.  Specifically, it is unclear whether requirements should be specified with `conan_cmake_configure()` or in a `conanfile.[py|txt]`.

Specifically:
1. If the user specified the requirements with `conan_cmake_configure()` then it is unclear what the requirement `PATH_OR_REFERENCE` option should point to.  Must it point to an empty file called `conanfile.[py|txt]`?
2. If the user specified the requirements in `conanfile.[py|txt]` then `PATH_OR_REFERENCE` must be refer to it, but now `conan_cmake_config()` must be an empty function?

^ Neither (1) nor (2) make sense to me, yet from the current documentation I do not see another approach.

**Comment by hwhsu1231** [comment]
@wouterbeek 

`conan_cmake_configure()` is just an **ALTERNATIVE WAY** for you to generate the Conan Recipe. You can actually **OMIT** this command if you already have your own `conanfile.txt` or `conanfile.py`  in your project and want to use it.

According to my experience, the two **REQUIRED** commands of cmake-conan are:

- `conan_cmake_autodetect()`
- `conan_cmake_install()`

As for `conan_cmake_configure()`, I seldom use it for now because I will prepare a Conan Recipe myself every time.

**Comment by wouterbeek** [comment]
Thanks for the info @hwhsu1231, that clarified things for me!  Closing this question...
