### ISSUE TITLE
Setting CMAKE_MODULE_PATH before first find_package() does not restore value

### ISSUE THREAD

**Issue by curlybeast** [conan-io/cmake-conan#570]
To test this:
```
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)
message(WARNING "CMAKE_MODULE_PATH (1) is set to: '${CMAKE_MODULE_PATH}'")

find_package(OpenSSL REQUIRED)

message(WARNING "CMAKE_MODULE_PATH (2) is set to: '${CMAKE_MODULE_PATH}'")
```

Patch used in conan_provider.cmake:

```
     # Invoke find_package a second time - if the first call succeeded,
     # this will simply reuse the result. If not, fall back to CMake default search
     # behaviour, also allowing modules to be searched.
+    message(WARNING "<-- Saving CMAKE_MODULE_PATH ('${CMAKE_MODULE_PATH}')")
     set(_cmake_module_path_orig "${CMAKE_MODULE_PATH}")
     list(PREPEND CMAKE_MODULE_PATH "${CONAN_GENERATORS_FOLDER}")
     if(NOT ${package_name}_FOUND)
+        message(WARNING "Finding another package")
         find_package(${package_name} ${ARGN} BYPASS_PROVIDER)
     endif()

+    message(WARNING "--> Loading CMAKE_MODULE_PATH ('${_cmake_module_path_orig}')")
    set(CMAKE_MODULE_PATH "${_cmake_module_path_orig}")
```

Output:
```
CMake Warning at cmake/conan_provider.cmake:504 (message):
  <-- Saving CMAKE_MODULE_PATH ('/home/mrussell/Source/mtx/cmake')
Call Stack (most recent call first):
  CMakeLists.txt:44 (find_package)


CMake Warning at cmake/conan_provider.cmake:508 (message):
  Finding another package
Call Stack (most recent call first):
  CMakeLists.txt:44 (find_package)


-- CMake-Conan: find_package(PkgConfig) found, 'conan install' already ran
CMake Warning at cmake/conan_provider.cmake:504 (message):
  <-- Saving CMAKE_MODULE_PATH
  ('/home/mrussell/Source/mtx/build-5280-debug/conan/build/Debug/generators;/home/mrussell/Source/mtx/cmake')
Call Stack (most recent call first):
  /opt/mtx-venv-5280/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FindOpenSSL.cmake:206 (find_package)
  cmake/conan_provider.cmake:509 (find_package)
  CMakeLists.txt:44 (find_package)


CMake Warning at cmake/conan_provider.cmake:508 (message):
  Finding another package
Call Stack (most recent call first):
  /opt/mtx-venv-5280/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FindOpenSSL.cmake:206 (find_package)
  cmake/conan_provider.cmake:509 (find_package)
  CMakeLists.txt:44 (find_package)


CMake Warning at cmake/conan_provider.cmake:512 (message):
  --> Loading CMAKE_MODULE_PATH
  ('/home/mrussell/Source/mtx/build-5280-debug/conan/build/Debug/generators;/home/mrussell/Source/mtx/cmake')
Call Stack (most recent call first):
  /opt/mtx-venv-5280/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FindOpenSSL.cmake:206 (find_package)
  cmake/conan_provider.cmake:509 (find_package)
  CMakeLists.txt:44 (find_package)


CMake Warning at cmake/conan_provider.cmake:512 (message):
  --> Loading CMAKE_MODULE_PATH ('')
Call Stack (most recent call first):
  CMakeLists.txt:44 (find_package)
```

You can clearly see it is setting the variable to an empty string.
I think this might be because of the extra `find_package()` call in that function.

**Comment by curlybeast** [comment]
This is based on the `conan_provider.cmake` in the `develop2` branch as of now.

**Comment by jcar87** [comment]
Hi @curlybeast  - thank you for your report. I've had a time to look into the root cause of this.

It turns out out this the interaction between 3 different things, some of which are bugs - you are right that nested calls to `find_package()` are at the heart of this, but there's more:

* The dependency provider cannot currently handle _nested_ calls to `find_package` - so some state is actually being overwritten by nested calls. When there are nested calls, the first one saves the "original" value, then a second call has its own "original" value, and stores it in the same variable (it's a macro, so it's the same variable in the same scope), overwriting the first one. On top of this - after the second call finishes (and returns control to the first one), it _clears_ the value, so when the first call "restores" the value, it is clear. This is a bug in and itself that needs to be fixed.

* This took me a while to figure out - but the reason you stumble into this particular problem is mostly because you're relying on find modules provided by CMake, and not by anything provided by Conan - is it possible that `openssl` was not listed as a Conan dependency? What's happening here is that the OpenSSL find module is calling the PKgConfig find module - the dependency provider hands it over to CMake's built in `find_package` after failing to find it from a config file. However, with Conan the issue is still present if we force `find_package(OpenSSL MODULE)`. 

* Conan generated files can actually _add_ values to `CMAKE_MODULE_PATH`, to enable calling `include(xxx)` for libraries that provide reusable CMake modules. By saving and restoring we actually risk losing this information. So there isn't an expectation that `CMAKE_MODULE_PATH` is restored exactly to the value it had before the outermost call to `find_package`, but rather, it should simply end with no prepending of the generators folder.

Given these 3 circumstances, I'm actually glad your proposed solution in https://github.com/conan-io/cmake-conan/pull/571/files  actually solves all 3 issues. 
Knowing this, I know what to test for exactly, so I'm happy to take over and write more specific set of tests

**Comment by curlybeast** [comment]
Thanks @jcar87, I found it harder writing the test case for this than the fix :) I think your input here will help.
Sadly, I'm new to the testing framework, so any help on this would be appreciated.

Regarding the `OpenSSL` situation. That's right, I'm not using it as a Conan dependency (in `conanfile.txt`). I'm using CMake from Python 3.8's PyPi module (to get the latest version ca. 3.27). So the CMake extensions there to find SSL are being used. The OpenSSL package is the System (which for me is on Red Hat Enterprise Linux 8) installed version **openssl-1.1.1k-9.el8_7.x86_64**.

For completion, this is my `conanfile.txt` (there are a combination of upstream / conan-center and self-built packages from Conan there), but the `CMakeLists.txt` is also using OpenSSL from the system, so quite the mixed bag :) - If you're wondering about the version number addition (i.e. `-1` or `-2`), it's because we also patch a lot of upstream software too.

```
[requires]
ace/6.0.1-2
activemq/5.18.2-0
activemq-cpp-library/3.9.4-1
agent++/4.5.4-1
apacheds/2.0.0.am26-0
boost/1.66.0-2
gtest/1.2.1-1
kafka/2.11-2.0.0-0
libnghttp2/1.49.0
mongo-cxx-driver/3.8.0
seagull/1.8.1-1
snmp++/3.4.10-1
snull/3.4-171-g718cbdf-3
xerces-c/3.2.4

[generators]
CMakeDeps
CMakeToolchain

[options]
xerces-c/*:shared=True
mongo-cxx-driver/*:shared=True
mongo-cxx-driver/*:polyfill=std
libnghttp2/*:shared=True
pkgconf/*:build_type=Release

[layout]
cmake_layout
```
