### ISSUE TITLE
build_requirements possible

### ISSUE THREAD

**Issue by tonka3000** [conan-io/cmake-conan#67]
Hey,

i have a little question. Is it possible to set build_requirements with the conan-cmake commands?

I have a complex app where i want to use conan-cmake, but know i see some "troubles" with the feature set. Using an existing conanfile.py would be possible, but then i have to provide a template python file, because i want to turn on/off features in my build (mostly via cmake).

Any ideas, suggestions, experience?

Greetings  
Tonka

**Comment by memsharded** [comment]
No, right now it is not implemented. The current solution is to provide your own conanfile and use it from your call, instead of specifying requires and other things as options in the cmake code.

```cmake
conan_cmake_run(CONANFILE conanfile.txt  # or relative build/conanfile.txt
                BASIC_SETUP CMAKE_TARGETS)
```

I suggest trying this, would it be a solution for you? Thanks!

**Comment by tonka3000** [comment]
Does the txt format support build_requirements?

> I suggest trying this, would it be a solution for you? Thanks!
It is exactly what i'm doing now. It is possible to use a cmake config template to create a py or txt conanfile, but it would be nice if it is integrated.

Generally i would prefer conanfile.py, but when i have many cmake variables to turn on/off features, i'm not sure how i can provide a good conanfile.py, because of the parameter handling. The project also has an integrated conanfile.py for exporting things.

**Comment by memsharded** [comment]
Yes, txt format uses ``[build_requires]``, you can use it too (and conanfile.py too).

Regarding the conanfile.py and the on/off variables, not sure, I'd need to have a look to it to make an idea.

Also, adding a BUILD_REQUIRES section to conan_cmake_run should be quite straightforward, so maybe that would be better for you. Would you like to contribute it? Thanks!

**Comment by tonka3000** [comment]
> Regarding the conanfile.py and the on/off variables, not sure, I'd need to have a look to it to make an idea.

Ok

> Also, adding a BUILD_REQUIRES section to conan_cmake_run should be quite straightforward, so maybe > that would be better for you. Would you like to contribute it? Thanks!

Yes, i will create a PR if i'm ready

**Comment by tonka3000** [comment]
> Yes, txt format uses [build_requires], you can use it too (and conanfile.py too).

Are you sure. I'm using 1.0.3 and i'm getting the follwoing error when i add this to txt
```
ConfigParser: Unrecognized field 'build_requires'
```

**Comment by lasote** [comment]
Hi! We've been thinking about this after your PR and we realized that requirements and build_requirements have no difference in a conanfile.txt because the meaning of a build_require is requiring something for building, but with a conanfile.txt there is no build method, right? You could use a virtualenv generator but a regular require will apply exactly the same.

What is exactly your use case? The implementation looks easy but maybe we are not applying correctly the build_requires, so will require some tests.

**Comment by memsharded** [comment]
No, it is not possible to use "private" qualifier in conanfile.txt. Do you have any version conflict upstream that forces you to do so? Because that is the main use case of "private" dependencies. As most likely usptream gtest is being used as "build_requires", there is no need to use "private" dependency for gtest in your conanfile.txt. Is there any other reason I am missing? Thanks!

**Comment by tonka3000** [comment]
I think i will use a conanfile.py and run it via cmake-conan. With that i have fine control over the requirements. 
Sometimes it happens the some project use a different gtest version and that's not so good, thats my main reason.

**Comment by memsharded** [comment]
Hi @tonka3000 

Sorry for the above, that is true, ``conanfile.txt`` doesn't have ``[build_requires]``, I made a mistake, that is from profiles.

Yes, I think if you want to have fine control, the best is to use a conanfile.py and use it from cmake-conan. Still transparent for cmake users, but you have better control.

Can this issue be closed now then? Thanks!

**Comment by tonka3000** [comment]
Hey @memshared,

You can close it
